Feature/TV-5-network-1 Проектирование по MVI для фичи, koin модули, базовые фрагменты и вью модель
android-finance-project/finance-accounting pull request #4
Opened 2022-10-19 18:32 UTC by korpatiy

2022-10-22 22:15 UTC, NLCodeTeam requested changes

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/data/model/ExchangeRate.kt
> +    @SerialName("currency_name")
Уверен, что все именно так должно быть?

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/data/network/Client.kt
> +class Client(private val baseUrl: String) {
Название плохое, клиент чего? банка?

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/data/remote/ExchangeRatesRepositoryImpl.kt
> +    override suspend fun getRates(): List<ExchangeRate> = client.get("rates").body()
строку можно вынести в константу

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/presentation/ui/ExchangeRatesFragment.kt
> +            exchangeCardFirst.textView.text = data[0].currencyName
А если data[0] не будет? и потом что такое data[0] ? цифру убрать в константу, чтобы было понятно, что там должно лежать по этой позиции

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/presentation/ui/ExchangeRatesFragment.kt
> +    private fun ExchangeRatesState.Error.handle() = Unit
так не бывает, раз сделал этот блок, хотя выводи временно в лог ошибку

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/presentation/ui/ExchangeRatesViewModel.kt
> +            _content.value = ExchangeRatesState.Error("Произошла ошибка")
Вынести в ресурсы

2022-10-22 22:15 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/management/data/model/ModelDao.kt
> +
Не надо добавлять пустые классы, вот когда понадобится в том пре и добавишь

2022-11-01 19:36 UTC, korpatiy commented on app/src/main/java/ru/rt/finance/features/exchangerates/data/model/ExchangeRate.kt
> +    @SerialName("currency_name")
Поправил уже на реальный ответ

2022-11-01 19:36 UTC, korpatiy commented on app/src/main/java/ru/rt/finance/features/exchangerates/data/network/Client.kt
> +class Client(private val baseUrl: String) {
Переименовал

2022-11-01 20:43 UTC, NLCodeTeam approved these changes

2022-11-01 20:43 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/MainActivity.kt
> +    private lateinit var binding: ActivityMainBinding
Вообще по идее binding зануляют, но тут это скорее всего неактуально

2022-11-01 20:43 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/MainFragment.kt
> +            is ExchangeRatesState.Loading -> {}
Убери Loading состояние, оно тебе не нужно

2022-11-01 20:43 UTC, NLCodeTeam commented on app/src/main/java/ru/rt/finance/features/exchangerates/presentation/ui/ExchangeRatesViewModel.kt
> +import kotlinx.coroutines.*
star imports

2022-11-02 15:03 UTC, merged